global:
  scrape_interval: 1m

scrape_configs:
  - job_name: lotus
    scrape_interval: 10s
    metrics_path: '/debug/metrics'
    static_configs:
      - targets: ['localhost:1234']

  - job_name: node_exporter
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9100']
